package com.company.enums;

public enum ErrorCodes {
    PRODUCT_NOT_FOUND,
    INTERNAL_SERVER_ERROR,
    UNAUTHORIZED,
    CONSTRAINT_VIOLATION,
    BAD_CREDENTIALS,
    JWT_TOKEN_EXPIRED,
    MALFORMED_TOKEN
}
